[package]
name = "tfapi"
version = "0.1.0"
authors = ["mansong1 <martin.ansong@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
